---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-helm-repo
  namespace: dev
spec:
  interval: 10s
  url: https://stefanprodan.github.io/podinfo


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-helm-repo
  namespace: dev
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
        namespace: dev
      version: '>4.0.0'      
  interval: 10s
  timeout: 5m
  prune: true
  releaseName: chart-from-helm-repo
  values:
    logLevel: debug
    replicaCount: 2
    ui:
      color: blue
