---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-from-git-helm
  namespace: flux-system
spec:
  interval: 10s
  # dependsOn:
  #   - name: infra-controllers
  #   - namespace: infra-controllers
  sourceRef:
    kind: GitRepository
    name: podinfo-child
    namespace: default
  path: ./helm-from-git
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: flux-system


# # ---
# # apiVersion: kustomize.toolkit.fluxcd.io/v1
# # kind: Kustomization
# # metadata:
# #   name: apps-from-git-source
# #   namespace: flux-system
# # spec:
# #   interval: 10s
# #   dependsOn:
# #     - name: apps-from-git-helm
# #   sourceRef:
# #     kind: GitRepository
# #     name: podinfo-child
# #     namespace: default
# #   path: ./source-from-git
# #   prune: true
# #   wait: true
# #   timeout: 5m0s
