# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: apps-from-git-helm
#   namespace: dev
# spec:
#   interval: 10s
#   sourceRef:
#     kind: GitRepository
#     name: podinfo-child
#     namespace: dev
#   dependsOn:
#     - name: infra-controllers
#       namespace: flux-system
#   path: ./helm-from-git
#   prune: true
#   wait: true
#   timeout: 5m0s
#   # targetNamespace: flux-system


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-from-helm-repo
  namespace: flux-system
spec:
  interval: 10s
  dependsOn:
    - name: apps-from-git-helm
      namespace: dev
  sourceRef:
    kind: GitRepository
    name: podinfo-child
    namespace: dev
  path: ./helm-from-helm-repo
  prune: true
  wait: true
  timeout: 5m0s


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-from-git-source
  namespace: flux-system
spec:
  interval: 10s
  # dependsOn:
  #   - name: apps-from-git-helm
  #     namespace: dev
  sourceRef:
    kind: GitRepository
    name: podinfo-child
    namespace: dev
  path: ./source-from-git
  prune: true
  wait: true
  timeout: 5m0s