apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-stefanprodan-podinfo
  namespace: dev
spec:
  interval: 10s
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-stefanprodan-podinfo
  namespace: dev
spec:
  interval: 10s
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: podinfo-stefanprodan-podinfo
    namespace: dev
  path: "./kustomize"
  prune: true
  timeout: 1m
  patches: 
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: podinfo-new
      target:
        kind: Deployment
        name: podinfo
        # namespace: dev
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo-new
        spec:
          minReplicas: 2
          maxReplicas: 2
      target:
        kind: HorizontalPodAutoscaler  
        name: podinfo
        namespace: default               
