apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-stefanprodan-podinfo
  namespace: dev
spec:
  interval: 10s
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-stefanprodan-podinfo
  namespace: dev
spec:
  interval: 10s
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: podinfo-stefanprodan-podinfo
    namespace: dev
  path: "./kustomize"
  prune: true
  timeout: 1m
  patches: 
    - patch: |
        - op: replace
          path: /metadata/name
          value: podinfo-new   
      target:
        kind: Deployment
        name: podinfo
        namespace: default
    - patch: |
        - op: replace
          path: /metadata/name
          value: podinfo-new   
      target:
        kind: HorizontalPodAutoscaler  
        name: podinfo
        namespace: default          

    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo-new
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: podinfo-new
            namespace: dev
          minReplicas: 2
          maxReplicas: 2
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
      target:
        kind: HorizontalPodAutoscaler  
        name: podinfo
        namespace: default               
