apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-mine-fork
  namespace: dev
spec:
  interval: 10s
  url: https://github.com/littlehau/podinfo
  ref:
    branch: master

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-mine-fork
  namespace: dev
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: podinfo-mine-fork
        namespace: dev
      version: '>4.0.0'    
  interval: 10s
  timeout: 5m
  prune: true
  releaseName: chart-from-git
  values:
    logLevel: debug
    replicaCount: 2
    ui:
      color: blue
    
